// prepare-args — demo 3: comma generated by EXPANSION doesn't split args
//
//   F(PAIR)   →  a , b        (ONE arg PAIR, expanded to "a, b")
//
// `F` collects its arguments FIRST (sees one arg `PAIR`), THEN expands that
// argument (`PAIR` → `a, b`). The comma generated by expanding `PAIR` is
// inside the expanded text of the single argument — it is NOT a separator
// between two arguments. Argument count is fixed BEFORE expansion.
//
//   WRONG mental model:   expand first  → PAIR → a, b → collect 2 args
//   RIGHT mental model:   collect args  → [PAIR] → expand → [a, b] → substitute
//
// Run:  ppstep demo/basic/18_3_prepare_pair.c
// Try:  b c F ; c ; s s   (count 1 arg first, then expand it to a, b)
//
// Trace (F(PAIR)):
//   1. calling  F          — collect ONE arg: x = raw "PAIR"
//      ── argument count already fixed at 1 ──
//   2. calling  PAIR       — expand the arg PAIR → "a, b" (EXPANDED form)
//   3. expanded F          — body x splices EXPANDED → a , b
//   4. rescanned F         — a , b: no macros → copy
//   Result:  a , b

#define F(x)    x
#define PAIR    a, b

F(PAIR)
